In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [39]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [40]:
data.drop(data.columns[0:3], axis = 1, inplace = True)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [41]:
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [42]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder(sparse_output=False)
geo = oe.fit_transform(data[['Geography']])
geo

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [43]:
### It cant work in ann ####
# data['Geography'] = geo.tolist()
# data[['Geography']].head()

In [44]:
oe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [45]:
geo_df = pd.DataFrame(geo, columns = oe.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [46]:
data = pd.concat([data.drop('Geography',axis = 1),geo_df],axis = 1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [47]:
with open('le.pkl','wb') as file:
    pickle.dump(le, file)

with open('oe.pkl','wb') as file:
    pickle.dump(oe, file)

In [48]:
X = data.drop('Exited', axis = 1)
y = data['Exited']

X_train, X_test, y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [49]:
X_train

array([[-0.23082038,  0.91509065, -0.94449979, ..., -0.99850112,
         1.71490137, -0.57273139],
       [-0.25150912, -1.09278791, -0.94449979, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [-0.3963303 , -1.09278791,  0.77498705, ..., -0.99850112,
         1.71490137, -0.57273139],
       ...,
       [ 0.22433188, -1.09278791,  0.58393295, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [ 0.13123255, -1.09278791,  0.01077067, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [ 1.1656695 ,  0.91509065,  0.29735181, ..., -0.99850112,
         1.71490137, -0.57273139]], shape=(8000, 12))

In [50]:
X_test

array([[-1.03768121,  0.91509065,  0.77498705, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [ 0.30708683,  0.91509065, -0.46686456, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [-1.23422423, -1.09278791,  0.29735181, ...,  1.00150113,
        -0.58312392, -0.57273139],
       ...,
       [-0.86182692,  0.91509065, -0.46686456, ..., -0.99850112,
        -0.58312392,  1.74601919],
       [-0.30323097, -1.09278791, -0.84897275, ..., -0.99850112,
         1.71490137, -0.57273139],
       [ 0.04847759,  0.91509065,  1.25262228, ..., -0.99850112,
         1.71490137, -0.57273139]], shape=(2000, 12))

In [51]:
with open('sc.pkl','wb') as file:
    pickle.dump(sc, file)

In [52]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [53]:
(X_train.shape[1],)

(12,)

In [54]:
#ANN Build

model = Sequential([
    Dense(64, activation='relu', input_shape= (X_train.shape[1],)),  #Hodden Layer 1
    Dense(32, activation='relu'), # HL2
    Dense(1, activation='sigmoid')    #OP Layer
])

model.summary()

d:\Projects_Aiml\Ann_Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
import tensorflow as tf
opt = tf.keras.optimizers.Adam(learning_rate = 0.01)
loss = tf.keras.losses.BinaryCrossentropy()
loss

In [56]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [57]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = 'logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tf_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [58]:
early_cb = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights= True)

In [59]:
history = model.fit(
    X_train, y_train, validation_data = (X_test,y_test), epochs = 100, callbacks = [tf_callback, early_cb]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.8328 - loss: 0.3954 - val_accuracy: 0.8510 - val_loss: 0.3536
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8547 - loss: 0.3542 - val_accuracy: 0.8610 - val_loss: 0.3432
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8549 - loss: 0.3505 - val_accuracy: 0.8545 - val_loss: 0.3431
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8590 - loss: 0.3426 - val_accuracy: 0.8590 - val_loss: 0.3464
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8580 - loss: 0.3417 - val_accuracy: 0.8645 - val_loss: 0.3453
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8604 - loss: 0.3392 - val_accuracy: 0.8670 - val_loss: 0.3450
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8586 - loss: 0.3393 - val_accuracy: 0.8555 - val_loss: 0.3497
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8635 - loss: 0.3340 - val_accuracy: 0.8605 - val_loss: 0.3511
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8622 - loss: 0.3331 - val_accuracy: 0.8695 - val_loss: 0.3374
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8615 - loss: 0.3337 - val_accuracy: 0.8610 - val_loss: 0.3460
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8640 - loss: 0.3280 - val_accuracy: 0.8640 - val_loss: 0.3413
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8646 - loss: 0.3260 - val_accuracy: 0.8630 - val_loss: 0.3407
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8660 - loss: 0.3240 - val_accuracy: 0.8620 - val_loss: 0.3512
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8685 - loss: 0.3241 - val_accuracy: 0.8610 - val_loss: 0.3505
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8665 - loss: 0.3202 - val_accuracy: 0.8620 - val_loss: 0.3472
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8676 - loss: 0.3178 - val_accuracy: 0.8625 - val_loss: 0.3533
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8689 - loss: 0.3173 - val_accuracy: 0.8685 - val_loss: 0.3400
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8671 - loss: 0.3159 - val_accuracy: 0.8620 - val_loss: 0.3459
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8719 - loss: 0.3127 - val_accuracy: 0.8705 - val_loss: 0.3511

In [60]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [61]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [62]:
#Run twice 
%tensorboard --logdir logs/fit/

Reusing TensorBoard on port 6006 (pid 2620), started 2:04:35 ago. (Use '!kill 2620' to kill it.)