In [22]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [23]:
model = load_model('model.h5')

with open('le.pkl','rb') as file:
     le = pickle.load(file)

with open('oe.pkl','rb') as file:
    oe =  pickle.load(file)

with open('sc.pkl','rb') as file:
    sc = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [24]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [25]:
# geo = oe.transform([[input_data['Geography']]]).toarray()
geo = oe.transform([[input_data['Geography']]])
geo_df = pd.DataFrame(geo, columns = oe.get_feature_names_out(['Geography']))
geo_df

d:\Projects_Aiml\Ann_Project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [26]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [27]:
input_df['Gender'] = le.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [30]:
input_df = pd.concat([input_df.drop('Geography', axis = 1), geo_df], axis = 1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [31]:
input_sc = sc.transform(input_df)
input_sc

array([[-0.52046273,  0.91509065,  0.10629772, -0.70174202, -0.26396987,
         0.80225696,  0.64376017,  0.97725852, -0.87097985,  1.00150113,
        -0.58312392, -0.57273139]])

In [32]:
prediction = model.predict(input_sc)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step

array([[0.03661731]], dtype=float32)

In [33]:
pred_prob = prediction[0][0]
pred_prob

np.float32(0.03661731)

In [34]:
if pred_prob > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.